### ISSUE TITLE
Appointment type should show on check in page

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#102]
On check in page we need to know if the appointment is for food only or for food and utilities so we need to show the appointment type on that modal.

**Comment by case-eee** [comment]
@pollygee Hi there! I'm a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there's already a solution in progress I'm happy to try helping out elsewhere. Thanks!

Also - I have the project setup and running on my local machine, but I'm not sure I fully understand this issue. Is the check-in page the homepage after logging in?

**Comment by pollygee** [comment]
Yay!  Welcome @case-eee we are so glad to have you.  Nobody is working on this issue currently so I'll assign it to you so people will know you're working on it.  I'll also add you to the repo so that you can fork it, that will make PR's easier!

Sorry the ticket isn't super clear.  You can join us on slack if you're interested https://rubyforgood.herokuapp.com/ it's a good place to be able to chat about the project if you want to get more involved.

But for this issue I'll try to clarify.  From the dashboard, with the seed data you should see a checkin button, this is when the volunteer will "check a client in" they will click this button and get the "check in modal".
![pantryscheduler](https://user-images.githubusercontent.com/10904005/30230017-55595bac-94b2-11e7-9df1-a9e213265a05.jpg)

On this modal 
![pantryscheduler](https://user-images.githubusercontent.com/10904005/30230059-89c0c2a4-94b2-11e7-8ad9-1cd766ed03bf.jpg)
we need to add the appointment type which will either be food, or food and utilities.
I'd say it should be above the USDA information.

Does that help clarify?  Let me know if anything still isn't super clear and welcome!  We're so grateful for the help!!

**Comment by case-eee** [comment]
hey @pollygee - sorry for the delay. thanks for the clarification! i do have one more question - do you want the clients to be able to change the appointment type from this modal? or do you just want to view the appointment type here? thanks!

**Comment by pollygee** [comment]
@case-eee no problem at all.  We have a separate model - _Users_ and a User creates an appointment, etc.  Basically a user is a volunteer who will be using the app, and a Client is someone who comes in to get food.  So, a User should be able to edit the appointment type, yes. I hope that helps!  Let me know if there's anything else that comes up that's not clear :)

**Comment by jgaskins** [comment]
Hey friends, since regulations require the Elizabeth House team to use a different solution, I'm just going through closing down issues.
