### ISSUE TITLE
Date picker should not show through client list

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#103]
![pantryscheduler](https://user-images.githubusercontent.com/10904005/28248844-4a1d9460-6a19-11e7-81ab-e0fb00ab0e76.jpg)
When creating an appointment, if you start to type a name and get a list come up, the date picker shows through the names and if you click on it....the date picker is selected.  We need to not see the date picker when looking at the list of names.

**Comment by caward12** [comment]
<img width="936" alt="screen shot 2017-07-28 at 11 04 03 am" src="https://user-images.githubusercontent.com/20826865/28728087-80f34556-7384-11e7-8620-7d82930b6f2b.png">
I can confirm this bug. I ran through set up instructions and ran localhost in chrome Version 59.0.3071.115. My operating system in MacOS Sierra 10.12.4.

**Comment by caward12** [comment]
I also can confirm using Safari version 10.1. 
<img width="1066" alt="screen shot 2017-07-28 at 11 02 23 am" src="https://user-images.githubusercontent.com/20826865/28728209-fbdd91b8-7384-11e7-8c08-cc4ad5a6ef6e.png">

**Comment by pollygee** [comment]
Thanks @caward12

**Comment by bolducp** [comment]
I've made a PR here (https://github.com/rubyforgood/pantry_scheduler/pull/107) that I think fixes this issue.
