### ISSUE TITLE
Current User email should show and Users should be able to log out

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#106]

**Comment by pollygee** [comment]
We need to display the current user that is logged in, and add a "log out" button so the current user can log out.

**Comment by charliecorrigan** [comment]
Hey there! I'll give this a try..I’m a first-time contributor and I noticed nobody was assigned to this issue. If someone else is already working on it, let me know!

**Comment by seanmarcia** [comment]
@charliecorrigan Apologizes that no one commented. The USDA is requiring the food bank to use software that they are providing so this project is on indefinite hold! If you hop into the [Ruby for Good](https://rubyforgood.herokuapp.com) slack we'd love to match you up with another project that needs help.
