### ISSUE TITLE
CSV import for clients

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#12]

**Comment by anubiskhan** [comment]
How's it going? This is my first time contributing to an open source project and I was hoping to help out with this issue. If there is someone else working on it already just let me know and I'll see if I can't help out somewhere else. Thanks!

**Comment by jgaskins** [comment]
@anubiskhan Thanks for your consideration here! Unfortunately, we've halted development on this project for now. The team we were developing it for ended up having to use a different solution.

If you'd like, there are still a lot of other Ruby for Good projects that could use contributions. Specifically, https://github.com/rubyforgood/diaper and https://github.com/rubyforgood/diaperpartner are two of the biggest ones.

Thanks again! 👍

**Comment by anubiskhan** [comment]
@jgaskins Sounds good. I will check out these other 2 projects. Thanks!
