### ISSUE TITLE
Set up Front End app

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#2]
We need a baseline front end app going so we can do asset compilation etc.  We will use React for this app.

**Comment by jgaskins** [comment]
Since we're using Rails 5.1, which supports webpack, [this article](http://pixelatedworks.com/articles/embracing-change-rails51-adopts-yarn-webpack-and-the-js-ecosystem/) might give us a bit of insight into how to get it going.

**Comment by jgaskins** [comment]
Setup in 96dbf34776065f6046cc81e13812d2ddd8c341bb
Integrated with React in 583818214695e2bce4f7a55fd329c05d35325c6a
