### ISSUE TITLE
Add Client model

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#5]
We need a Model and Controller for Client.

Clients have:
  - first_name (required)
  - last_name (required)
  - address (required)
  - phone_number
  - cell_number
    -require that one number is present, either mobile or home
  - email
  - county (required)
  - zip (required)
  - num_adults (required)
  - num_children (required)
  - USDA_cert_date (date -can be null, N/A if country is AA or HO)

**Comment by ajohnson052** [comment]
it may be useful to have an `authorized_receiver` as well
