### ISSUE TITLE
Close modal window on Notes when saving

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#67]
When a user clicks `save` after creating a note on an appointment, the modal window should close.

**Comment by chantal66** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by chantal66** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by pollygee** [comment]
Hi @chantal66!!  Thanks so much for reaching out!  We are putting work on this app on hold at the moment (apologies I thought I took the "help wanted" label off all of our tickets).  We are part of an organization called RubyForGood and there are lots of projects that need help!  You can find more info here http://rubyforgood.org/projects.html if you're looking for somewhere to contribute.  We have a link to a slack channel invite on that site too!  You could join our slack and join a community of people who can help you find a place to contribute, and also could help you if you had any stumbling blocks along the way as well!   

Thanks so much!

**Comment by chantal66** [comment]
thank you for letting me know. :)
