### ISSUE TITLE
Should be able to click on Notes after Creating them

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#68]
When on dashboard, if I create a note and save, then I can not click on that note again without refreshing the page.  I want to be able to click on the note and not have to refresh the page.

**Comment by jgaskins** [comment]
I can't seem to reproduce this. I added a note, it showed up, I closed the modal and then clicked the notes button for that client again and the note I wrote was there without a refresh.

**Comment by pollygee** [comment]
I don't know if it's browser dependent?  I definitely had this problem over and over.

**Comment by pollygee** [comment]
I'm not having a problem with this anymore either.  Maybe it was a specific order I did things in?  I'll close this and hope not to see it again!
