### ISSUE TITLE
Mock-ups (first pass)

### ISSUE THREAD

**Issue by megbutler** [rubyforgood/pantry_scheduler#76]
Clickable prototype (click the screen to see the blue clickable hotspots) https://projects.invisionapp.com/share/J8BUMTDWT#/screens/235312816

Feedback welcome!

**Comment by jgaskins** [comment]
Hey Meghan, it's not that I think your mockup isn't baller, but I'm just closing down issues since the Elizabeth House team had to go with a different solution. 😢
