### ISSUE TITLE
Remove an appointment from the dashboard after checkin

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#78]
Currently when you finish a checkin, it shows the time of the checkin.  I would prefer for that name to be removed from the list.  Or maybe it can be pushed to the bottom and greyed out or something visually to clear the clutter of those who have already been checked in.

**Comment by jgaskins** [comment]
Having some sort of animation for pushing this to the bottom might be ideal. Clicking check-in and seeing the client disappear from under your cursor might be a jarring UX.

The [`MagicMove`](https://github.com/ryanflorence/react-magic-move) component might be a decent solution for this.

**Comment by pollygee** [comment]
This was Jess and Megan's design, I really like it.  I pitched it to Linda on Saturday she loves it.  

Once you've checked a client in it makes sense that it wont show up on the checkin page once you've checked them in.  It's less clutter to look at and not confusing about who has come and who hasn't.
