### ISSUE TITLE
Add features to creating an appointment

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#79]
When creating an appointment, Food should be checked automatically, almost all appointments are for food.

Also the Address needs to show.  At time of making appointment, the volunteer will verify this information, if it is updated, it needs to update Client.

**Comment by pollygee** [comment]
@bolducp has addressed the food being checked automatically.  The address still needs to be added as editable fields.

**Comment by hughgardiner** [comment]
Hey @pollygee I will work on adding the address fields to the appointments screen!

**Comment by pollygee** [comment]
@gardinerhugh6 awesome!  Thanks so much.  Invited you to collaborate with the project, so when you accept that invite please assign this issue to yourself so everyone can see you're working on it.  Let me know if you have any questions and feel free to join our pantry channel on ruby for good slack if you want to join us!!  https://rubyforgood.herokuapp.com/  Welcome and we're so grateful you're here!

**Comment by hughgardiner** [comment]
Good evening Polly! i just created a pull request for this story (https://github.com/rubyforgood/pantry_scheduler/pull/117) and I was wondering if there was someone who needed to review the changes I made before merging them

**Comment by pollygee** [comment]
Awesome @gardinerhugh6!!  Thanks so much.  Yes, all code needs to be reviewed before it gets merged.  I wont have time tonight, I will try to get to it tomorrow.  I'll get back to you soon.  Thanks again!

**Comment by hughgardiner** [comment]
https://github.com/rubyforgood/pantry_scheduler/pull/117
