### ISSUE TITLE
USDA cert date needs to be an editable field for checkin

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#87]
When checking someone in if we re-certify them we need to be able to update the UDSA cert date.

**Comment by ewiggins** [comment]
@pollygee I'll take this one!

**Comment by pollygee** [comment]
Ok @ewiggins that's awesome! Thanks and welcome!  I'll send you an invite to contribute, please assign this ticket to yourself when you accept the invite so others will know this ticket is taken.  Let me know if you need more clarification on the workflow.  

Here's a bit more info to get you started.  Clients need to "re-certify" once a year.  So if a client comes in and their certification date has passed a year ago then we need to have them sign a new paper to re-certify.
There is a checkin modal when you click `checkin` from the dashboard.  From that modal the volunteer will see that they need to sign a new paper.  At that point they need to be able to update the date.  We probably want this to default to `today` but be able to be changed (in case they had already filled out the paper on the last visit or something but the date wasn't updated - we keep the physical paper at Elizabeth House).

**Comment by ewiggins** [comment]
@pollygee Ok. I'll reach out if I need more clarification.

**Comment by ewiggins** [comment]
Hey @pollygee , I'm having some trouble getting the react to render. This is what I get when I install yarn, run ./bin/webpack-dev-server and then run rails s. Any ideas? I added 'Hello' to make sure the application.js was loading. 
![screen shot 2017-09-14 at 7 54 15 pm](https://user-images.githubusercontent.com/4694248/30460739-ba5188b2-9986-11e7-87a7-c03dc7fe992b.png)

**Comment by pollygee** [comment]
@ewiggins that's weird I haven't seen that before.  You've followed **all** the instructions in the README with the seed data and all that?  I would try stopping and starting the servers again, and maybe even close terminal and open it again.  Also do you have React Dev tools installed in your browser?  If so are you seeing any react errors?

**Comment by ewiggins** [comment]
@pollygee Yea I've followed them all. For some reason, the react app isn't loading. I'll keep troubleshooting. Just wanted to see if you've seen this before. 

![screen shot 2017-09-14 at 9 50 03 pm](https://user-images.githubusercontent.com/4694248/30462890-b32f935c-9996-11e7-83f7-f6c089540f48.png)

**Comment by ewiggins** [comment]
Hey @pollygee , doesn't look like the pantry wants to play nice with me :(. I unassigned myself from this issue.

**Comment by jgaskins** [comment]
@ewiggins Just to clarify, is that "hello" message rendered by JS?

I'd like to help you get it working if I can. Would you be up for pairing on it?

**Comment by ewiggins** [comment]
I would too. Would love to help out. Yep, so the application.js is
rendering fine( I just placed a <h1> Hello </h1> in application.js to make sure it's rendering. I'm getting the console.log message as well)  , but it's not picking up the React app.


When are you free to pair? I'm making a habit of working on side projects
Sunday afternoon and each evening. Today and tomorrow will be hectic so my
schedule will be different, but Sunday should be clear.

**Comment by jgaskins** [comment]
Sure, I can do Sunday (any time's fine). Could you send a calendar invite to jgaskins@gmail.com so I don't forget? :-)

**Comment by ewiggins** [comment]
Done! I usually go to the Arlington Central Library during that time. Not
sure where you live. Or we can do hangouts. I also have Screen Share/Slack
Call.

**Comment by jgaskins** [comment]
To follow up here, the issue seems to have been caused by our `webpacker` configuration not playing well with Cloud9. We figured out a workaround, though, and I added #112 to make it so that workaround isn't needed.

**Comment by ewiggins** [comment]
Sweet! I'll pull down Master.

**Comment by jgaskins** [comment]
It's not on `master` yet, but you can check out `upgrade-webpack` and see if it works for you. I think you'll just need to re-run `bundle install` and `yarn install`, but then `rails s` should work. Admittedly, I ran it on a fresh C9 instance, but it should still be good.
