### ISSUE TITLE
"Check in" button should be disabled when editing a client's info in checkin modal

### ISSUE THREAD

**Issue by pollygee** [rubyforgood/pantry_scheduler#97]
Currently the workflow is that if you're checking a client in and edit their info you need to check "save" then "checkin" and I think this is a confusing workflow.   We need to either disable "checkin" until you've saved or have some other way to alert the user that you must save before checkin.  Currently if you click checkin then all edits are lost.

**Comment by MiguelSilva1997** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by seanmarcia** [comment]
@MiguelSilva1997 I just updated the project README to let everyone know that the USDA is requiring the food bank to use software that they are providing so this project is on indefinite hold! If you hop into the [Ruby for Good](https://rubyforgood.herokuapp.com) slack we'd love to match you up with another project that needs help.
